server:
  port: 8082

#debug: true
logging:
  group:
    ebank: com.doris.controller, com.doris.service
    iservice: com.alibaba
  level:
    root: info
    # 设置某个包的日志级别
    com.doris.controller: debug
    # 设置分组，对某个组设置日志级别
    iservice: warn
  # 日志模版
  pattern:
#    console: "%d - %m %n"
#    console: "%d %clr(%Sp) --- [%16t] %clr(%-40.40c){cyan} : %m %n"
  file:
    name: server.log
  logback:
    roollingpolicy:
      max-file-size: 5kb
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
